[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
#TODO
quote = "1.0.38"
syn = { version = "2.0.96", features = ["extra-traits", "full"]}
